### ISSUE TITLE
Rhum v2.0 (Release Date: TBD)

### ISSUE THREAD

**Issue by crookse** [drashland/rhum#75]
## Tasks

- [x] CLI options (#74)
- [x] Script to generate test file (#44)
- [x] Mock not taking arguments (#28)
- [x] Ability to assert what arguments a method was called with (#21)
- [x] Skip functionality (#16)
- [x] real-time results (#78)
- [x] `make` subcommand (#44)
- [x] ~Ability to test non-public members (#19)~ (Won't do. Users should use the Reflect API.)
- [x] ~`--ignore` option (#82)~ (Logic is no longer needed. `run` command checks files for Rhum namespace now.)
- [ ] Rhum lifecycle diagram (#81)
- [ ] Documentation (https://github.com/drashland/website/issues/227)
    - [ ] Add v2.0 docs
    - [ ] Add migration guide
    - [ ] Archive v1.0 docs, but let it be accessible through an Archive section

**Comment by ebebbington** [comment]
Maybe https://drash.land/rhum/v1, .../v2 ?

**Comment by crookse** [comment]
@ebebbington, yea that will work. in the sidebar, we'll have an Archive section and a v1.0 link. That link will point to drash.land/rhum/v1.

drash.land/rhum will be updated to have v2 documentation. the good thing about our documentation setup is that we can build separate vue applications for both v1 and v2 documentation.

**Comment by ebebbington** [comment]
Oh wait, can we reuse the v1 docs? I’m thinking we may as well do this for each module (fml) but v2 docs would still have stuff from v1

**Comment by crookse** [comment]
Yea, so what we'll do is build the v1 docs and put the build in a /v1 directory. That covers archiving the v1 docs. Then we can iterate over our vue app to make it v2. i do think we should make a branch for v1 though and just keep it alive in case we need to update v1 docs and rebuild the vue app.

**Comment by ebebbington** [comment]
nice one on the description!

**Comment by crookse** [comment]
Changing release date to TBD. Reason being that we realized Rhum v2.0.0 is dependent on the CLI service; and the CLI service needs more planning.

**Comment by crookse** [comment]
Pushing back release date. No time to work on this. Will aim for July 1, 2021

**Comment by crookse** [comment]
Setting release date TBD... waiting for deno std to be stable. :/

**Comment by crookse** [comment]
closing this v2 plan. no longer needed since we're moving towards being a test double module
